lighthouse:
  name: "lighthouse"
  ip: "192.168.100.1/24"
  # Local lighthouse
  routable_ip: "172.17.0.2"
  # Remote lighthouse
  #routable_ip: "164.90.172.129"
  routable_port: "4242"

resources:
  - name: "laptop1"
    ip: "192.168.100.2/24"
    groups:
      - laptops

  - name: "laptop2"
    ip: "192.168.100.3/24"
    groups:
      - laptops

  - name: "server1"
    ip: "192.168.100.4/24"
    groups:
      - servers

  - name: "server2"
    ip: "192.168.100.5/24"
    groups:
      - servers
