lighthouse:
  name: "lighthouse"
  ip: "192.168.100.1/24"
  routable_ip: "172.17.0.2"
  routable_port: "4242"

resources:
  - name: "laptop"
    ip: "192.168.100.5/24"
    groups:
      - laptop
      - ssh

  - name: "server1"
    ip: "192.168.100.9/24"
    groups:
      - servers

  - name: "server2"
    ip: "192.168.100.10/24"
    groups:
      - servers
